autoclip: false
autoimport: false
cliptimeout: 45
exportkeys: false
nopager: false
notifications: false
parsing: true
path: /Users/adrian/.password-store
safecontent: false
mounts:
    feram: /Users/adrian/Dropbox/Projects/feram/meta
