root:
  askformore: false
  autoclip: false
  autoprint: false
  autoimport: false
  autosync: true
  check_recipient_hash: false
  cliptimeout: 45
  concurrency: 1
  editrecipients: false
  nocolor: false
  noconfirm: false
  nopager: false
  notifications: false
  path: gpgcli-gitcli-fs+file:///Users/adrian/.password-store
  recipient_hash: {}
  safecontent: false
  usesymbols: false
mounts:
  feram:
    askformore: false
    autoclip: false
    autoprint: false
    autoimport: false
    autosync: true
    check_recipient_hash: false
    cliptimeout: 45
    concurrency: 1
    editrecipients: false
    nocolor: false
    noconfirm: false
    nopager: false
    notifications: false
    path: gpgcli-gitcli-fs+file:///Users/adrian/Projects/feram/meta
    recipient_hash:
      .gpg-id: 354231343642434635463132354438353943373635344131313539383545453138444536323234420aa69f73cca23a9ac5c8b567dc185a756e97c982164fe25859e0d1dcc1475c80a615b2123af1f5f94c11e3e9402c3ac558f500199d95b6d3e301758586281dcd26
    safecontent: false
    usesymbols: false
