root:
  askformore: false
  autoimport: false
  autosync: true
  cliptimeout: 45
  noconfirm: false
  nopager: false
  path: /Users/adrian/.password-store
  safecontent: false
  usesymbols: false
  nocolor: false
mounts:
  feram:
    askformore: false
    autoimport: false
    autosync: true
    cliptimeout: 45
    noconfirm: false
    nopager: false
    path: /Users/adrian/Projects/feram/meta
    safecontent: false
    usesymbols: false
    nocolor: false
version: 1.6.11
